#!/bin/bash
# Huong dan: Go lenh curl o duoi trong terminal ssh
# curl https://raw.githubusercontent.com/zaichiict/zcms-centos6/master/install_zcms_production | sh

#Config Color
BG_GREEN="\e[42m\e[97m"
BG_NC="\e[0m\n"

#Config db password
dbUsername="postgres"
dbPassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 22 | head -n 1)

cd ~
curl -O http://vault.centos.org/RPM-GPG-KEY-CentOS-6

#Install base package
yum install -y wget nano git tree zip unzip tar man gcc gcc-c++ make

#Add repo
cd /etc/yum.repos.d
wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
wget http://rpms.famillecollet.com/enterprise/remi.repo
wget https://raw.githubusercontent.com/zaichiict/zcms-centos6/master/src/nginx.repo
rpm -Uvh epel-release-6*.rpm
echo "y" | yum localinstall http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm
echo "y" | yum --enablerepo=remi,remi-php56 install -y perl nginx redis postgresql94-server mysql-server memcached php php-devel pcre-devel php-fpm php-pdo php-mcrypt php-redis php-pgsql php-gd php-xml php-recode php-mbstring php-mysql php-intl php-opcache php-pear php-pecl-memcache php-pecl-memcached php-apc libxml2-devel

service postgresql-9.4 initdb
sed -i '18iexclude=postgresql*' /etc/yum.repos.d/CentOS-Base.repo
sed -i '28iexclude=postgresql*' /etc/yum.repos.d/CentOS-Base.repo
sed -i '10i-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT' /etc/sysconfig/iptables
sed -i '11i-A INPUT -p tcp -m state --state NEW -m tcp --dport 5432 -j ACCEPT' /etc/sysconfig/iptables
sed -i '11i-A INPUT -p tcp -m state --state NEW -m tcp --dport 3306 -j ACCEPT' /etc/sysconfig/iptables
perl -i -pe 's/ident/md5/g' /var/lib/pgsql/9.4/data/pg_hba.conf
echo "host  all  all  0.0.0.0/0  md5" >> /var/lib/pgsql/9.4/data/pg_hba.conf
echo "listen_addresses='*'" >> /var/lib/pgsql/9.4/data/postgresql.conf
ln -s /usr/pgsql-9.4/bin/pg_config /usr/bin/pg_config
chkconfig postgresql-9.4 on
service postgresql-9.4 start
su postgres -c "psql --command \"ALTER USER $dbUsername WITH PASSWORD '$dbPassword'\"";
su postgres -c "psql --command \"CREATE DATABASE zcms\"";
setsebool -P httpd_can_network_connect 1

#Config MySQL
service mysqld start
/usr/bin/mysql_secure_installation << EOF

y
$dbPassword
$dbPassword
y
y
y
y
EOF
mysql --user="root" --password="$dbPassword" -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$dbPassword';"
mysql --user="root" --password="$dbPassword" -e "CREATE DATABASE zcms;"
service iptables restart

#Install phpMyAdmin
rm -fr /etc/nginx/conf.d/default.conf
cd /etc/nginx/conf.d/
wget https://raw.githubusercontent.com/zaichiict/zcms-centos6/master/src/default.conf
cd ~
wget https://files.phpmyadmin.net/phpMyAdmin/4.4.11/phpMyAdmin-4.4.11-english.tar.xz
unxz phpMyAdmin-4.4.11-english.tar.xz
tar -xvf phpMyAdmin-4.4.11-english.tar
mv phpMyAdmin-4.4.11-english /usr/share/nginx/html/phpmyadmin
mv /usr/share/nginx/html/phpmyadmin/config.sample.inc.php /usr/share/nginx/html/phpmyadmin/config.inc.php
rm -fr phpMyAdmin-4.4.11-english.tar
RD_COOKIE_PHPMYADMIN=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 32 | head -n 1)
perl -i -pe "s/cfg\['blowfish_secret'\] = ''/cfg\['blowfish_secret'\] = '$RD_COOKIE_PHPMYADMIN'/g" /usr/share/nginx/html/phpmyadmin/config.inc.php
chmod 755 /usr/share/nginx/html/phpmyadmin/
chmod 755 /usr/share/nginx/html/
chcon -Rt httpd_sys_rw_content_t /usr/share/nginx/html/

rm -fr /etc/php.ini
cd /etc/
wget https://raw.githubusercontent.com/zaichiict/zcms-centos6/master/src/php.ini
cd /etc/nginx/conf.d/
wget https://raw.githubusercontent.com/zaichiict/zcms-centos6/master/src/zcms-demo.conf
wget https://raw.githubusercontent.com/zaichiict/zcms-centos6/master/src/zcms.conf.example
cd /etc/php.d/
wget https://raw.githubusercontent.com/zaichiict/zcms-centos6/master/src/60-phalcon.ini
cd /usr/bin/
wget https://raw.githubusercontent.com/zaichiict/zcms-centos6/master/src/zcms.sh
mv /usr/bin/zcms.sh /usr/bin/zcms
chmod +x /usr/bin/zcms

#Install Phalcon
cd ~
wget https://github.com/phalcon/cphalcon/archive/phalcon-v2.0.4.tar.gz
tar vfx phalcon-v2.0.4.tar.gz
cd cphalcon-phalcon-v2.0.4/build/
./install
cd ~
rm -fr phalcon-v2.0.4.tar.gz
rm -fr cphalcon-phalcon-v2.0.4

chkconfig php-fpm on
chkconfig redis on
chkconfig postgresql-9.4 on
chkconfig nginx on
chkconfig mysqld on

#Install ZCMS for Command
zcms install

#Create zcms demo website
chmod 755 /home/
cd /home/
zcms create zcms-demo
chcon -Rt httpd_sys_content_t /home/

#Restart service
zcms restart

#Clean YUM 
yum clean all

cd ~
echo "---------------------------------------------------

-----------  INSTALL ZCMS SUCCESSFULLY  -----------
---------------------------------------------------
---------------------------------------------------
- DB INFO:                                        -
- DB USERNAME   : postgres                        -
- DB PASSWORD   : $dbPassword          -
- MySQL PASSWORD: $dbPassword          -
- Please change your password for postgres, mysql -
===================================================
= WARNING: PLEASE REMEMBER AND REMOVE THIS FILE   =
===================================================" > install_info_db.txt

clean

echo "---------------------------------------------------"
echo "---------------------------------------------------"
echo "-----------  INSTALL ZCMS SUCCESSFULLY  -----------"
echo "---------------------------------------------------"
echo "---------------------------------------------------"
echo "- DB INFO:                                        -"
echo "- DB USERNAME   : postgres                        -"
echo "- DB PASSWORD   : $dbPassword          -"
echo "- MySQL PASSWORD: $dbPassword          -"
echo "- Please change your password for postgres, mysql -"
echo "---------------------------------------------------"
echo "- READ INFO DATABASE: # nano ~\\install_info_db.txt-"
echo "---------------------------------------------------"
echo "-                ZCMS Command Line                -" 
echo "---------------------------------------------------"
echo "- Command       : zcms [OPTION]                   -" 
echo "- OPTION:start|update|create|new|restart|install) -"
echo "---------------------------------------------------"